import './components/sections/hero'
import './scripts/materiaPrima/agregarMP'
import './scripts/modal/abrirModal'
import './scripts/modal/cerrarModal'
import './components/sections/optionsSection'
import './components/sections/gestionMpSection'